- method: GET
  path: /user
  handler: { class: Ruubik\Controller\IndexController, method: renderPage }

- method: GET
  path: /install/check
  handler: { class: Ruubik\Controller\InstallCheckController, method: checkSystem }