- method: GET
  path: /user
  handler: { class: Ruubik\Controller\IndexController, method: renderPage }

- method: POST
  path: /user2
  handler: { class: Ruubik\Conttoller\IndexController:class, method: renderPage }